[Client]
    addr = "127.0.0.1:3306"
    dsn ="root:Qwer1234@@tcp(81.68.89.3:3306)/lvxz_db?charset=utf8mb4&parseTime=True&loc=Local"
    readDSN = ["root:Qwer1234@@tcp(81.68.89.3:3306)/lvxz_db?charset=utf8mb4&parseTime=True&loc=Local"]
    active = 20
    idle = 10
    idleTimeout ="4h"
    queryTimeout = "200ms"
    execTimeout = "300ms"
    tranTimeout = "400ms"
